### ISSUE TITLE
Suggestions on dragome-production.js

### ISSUE THREAD

**Issue by bertung** [dragome/dragome-sdk#89]
Progress bar should not be implemented by Dragome. A callback method supplied by Dragome may be listened by the third party developers so that they can create a progress bar themselves. dragome.css and other stylesheets are not necessary for a core functionality. hashtable, deflate, console helpers, String, application and deflate-main should be consolidated into a single javascript file called runtime.js, and called right after atmosphere.js. I would also question the need of atmosphere.js in the production code. The name of the compiled code must be configurable, "webapp-x.js" should not be forced. 

Dragome should be able to run right from a web worker. DOM related hardwired dependencies must be separated to another package and split from the code sdk.

On the application launch side, why would you load the complied code using XHR and eval the loaded code? I also couldn't understand the need to receive the compiled code in array buffer format. Using script method you supply should be sufficient and faster.

**Comment by fpetrola** [comment]
Yes, these are pending improvements. 
Modular css and js inclusion needs to be implemented not only for dragome extra modules such as Guia (the one which includes progress implementation), also needs to be used to give the possibility of  third party addons development. In particular 
I'm thinking about how to pack a module to have all required files in just one container or something like this. May be a simple jar could solve this, mapping resources to web by convention, and giving the chance to make a custom mapping too.
Also I'd like to split code into different js files, for example one js for each important jar files. This should allow a better usage of browser cache in terms there are several libraries that don't perceive changes at all in app development (ex: jre, w3c).

All js files can be consolidated in just one jar called compiled.js, but it's only available in servlet container running mode, not in standalone js generation mode for now. It's implemented using wro4j and you have to include this js in html: dragome/dragome.js

For webworker approach I need to make some research in order to understand how to share code between different workers as classes definitions cannot be processed multiple times.

About XHR compiled code it's about compression. When dragome-production.js is used the compiled coded requested is compressed and needs to be transferred like this. But if you use dragome-debug.js compiled code will be less compressed but is transferred by standard request.

**Comment by bertung** [comment]
I think Dragome should not introduce a custom compression/decompression feature for the compiled code. Instead, compiler can create a .gz(gzipped) extension of the code and let the developers worry about how to deliver the compressed code to the browser (using filters,etc). If these deflate javascript files are for just decompressing the compiled code I would think that is a over kill and waste of cpu resources at the client side. Let the developer deal with that but it would be good idea to give an option to also produce the gzipped version of the compiled code. That would speed up things tremendously.

**Comment by fpetrola** [comment]
In fact current mechanism is very similar to this, 3 types of compiled code are generated:

1. Uncompressed code (loaded by dragome-resources/dragome-debug.js)
2. Packed and minimized code (loaded by dragome/dragome.js)
3. Compressed code (loaded by dragome-resources/dragome-production.js)

And the developer can choose between any of these options.

**Comment by fpetrola** [comment]
These 3 types of generated code are fixed, what we can do is provide a mechanism for custom delivery of generated code, where you can treat both server and client side data in any way is required for the developer.

**Comment by bertung** [comment]
Great idea, but calling the uncompressed code "debug" and the other one "production" may make things a little awkward. Calling them "standard" and "compressed" accordingly or something similar would make more sense to the developer.

**Comment by bertung** [comment]
I am closing this one.
